In [1]:
#Pandas is one of the powerful libraries of Python and is used to handle dataframes and deal with missing values, insertion, and deletion of the values 
#And grouping the values based on conditions, sliciinga nd indexing, joining tables, and reshaping the tables is all possible with pandas.
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df=pd.read_csv(r"C:\FSDS\Python Concepts with Codes\Notes and Code Explanation Notes\Pandas\data.csv")
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [4]:
id(df)

2116065651952

In [5]:
#records  are 195

len(df)

195

In [6]:
#These are the attribute present in the dataset
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [7]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [8]:
df.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [9]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [10]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [11]:
df.head

<bound method NDFrame.head of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [12]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [14]:
#TO print the whole data in a reversed manner
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [15]:
#TO print the whole data
df[::1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [16]:
#TO print records between 10 till 50 with a recors gap in between 
df[10:50:2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.7000,Upper middle income
12,Belgium,BEL,11.200,82.1702,High income
14,Burkina Faso,BFA,40.551,9.1000,Low income
16,Bulgaria,BGR,9.200,53.0615,Upper middle income
18,"Bahamas, The",BHS,15.339,72.0000,High income
20,Belarus,BLR,12.500,54.1700,Upper middle income
22,Bermuda,BMU,10.400,95.3000,High income
24,Brazil,BRA,14.931,51.0400,Upper middle income
26,Brunei Darussalam,BRN,16.405,64.5000,High income
28,Botswana,BWA,25.267,15.0000,Upper middle income
30,Canada,CAN,10.900,85.8000,High income
32,Chile,CHL,13.385,66.5000,High income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
36,"Congo, Rep.",COG,37.011,6.6000,Lower middle income
38,Comoros,COM,34.326,6.5000,Low income
40,Costa Rica,CRI,15.022,45.9600,Upper middle income
42,Cayman Islands,CYM,12.500,74.1000,High income
44,Czech Republic,CZE,10.200,74.1104,High income
46,Djibouti,DJI,25.486,9.5000,Lower middle income
48,Dominican Republic,DOM,21.198,45.9000,Upper middle income

In [17]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [18]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [23]:
df[['CountryName','CountryCode','IncomeGroup']]
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [25]:
df[['BirthRate','InternetUsers']]

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [27]:
df_cat=df[['CountryName','CountryCode','IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [28]:
df_num=df[['BirthRate','InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [29]:
print(len(df.columns))
print(len(df_cat.columns))

5
3

In [30]:
print(df.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [31]:
print(df_cat.columns)

Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [32]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [34]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [35]:
#Transpose converts rows to columns and columns to rows
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

In [42]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

In [43]:
#How to rename columns
df.columns=['a', 'b', 'c', 'd', 'e']

In [44]:
df.head()

                      a    b       c     d                    e
0                 Aruba  ABW  10.244  78.9          High income
1           Afghanistan  AFG  35.253   5.9           Low income
2                Angola  AGO  45.985  19.1  Upper middle income
3               Albania  ALB  12.877  57.2  Upper middle income
4  United Arab Emirates  ARE  11.044  88.0          High income

In [45]:
#How to get back the column names back

df.columns=['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup']

In [46]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [48]:
#how to find a specific information using subset
df_cat=df[['CountryName','CountryCode','IncomeGroup']]
df_cat

     CountryName CountryCode          IncomeGroup
10    Azerbaijan         AZE  Upper middle income
11       Burundi         BDI           Low income
12       Belgium         BEL          High income
13         Benin         BEN           Low income
14  Burkina Faso         BFA           Low income

In [51]:
df_cat=df[10:15][['CountryName','CountryCode','IncomeGroup']]
df_cat

     CountryName CountryCode          IncomeGroup
10    Azerbaijan         AZE  Upper middle income
11       Burundi         BDI           Low income
12       Belgium         BEL          High income
13         Benin         BEN           Low income
14  Burkina Faso         BFA           Low income

In [54]:
#Arithmatic  operation using 2 columns
df['New Column']=df.BirthRate*df.InternetUsers

In [62]:
#How to add a new column to a dataset
df.head(5)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,New Column
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720

In [61]:
#Here we have added new columns which is a multiplication of Birthrate*InternetUsers

In [63]:
len(df.columns)

6

In [64]:
df=df.drop('New Column', axis=1)

In [65]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [66]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [67]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [68]:
df.InternetUsers<2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [69]:
#To get records instead of false, we need to use df[df[]]
low_edu=df[df.InternetUsers<2]

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [70]:
len(df[df.InternetUsers<2])

9

In [71]:
#Number of countries with birthrate grater than 40
len(df[df.BirthRate>40])

12

In [73]:
#To get records instead of false, we need to use df[df[]]
low_internet=df[df.InternetUsers<2]
low_internet

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [76]:
high_birthrate=(df[df.BirthRate>40])
high_birthrate

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [88]:
#If we want to get records commining both the conditions the we ue and operator
filter1=df.InternetUsers<2
filter2=df.BirthRate>40
filter3=df[filter1 & filter2]
print(filter3)
print(len(filter3))

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income
3